### ISSUE TITLE
New installations are broken because of upstream issue for detectron2

### ISSUE THREAD

**Issue by stweil** [bertsky/ocrd_detectron2#26]
Building works, but running `ocrd-detectron2-segment` with `make check` [raises an exception](https://github.com/OCR-D/ocrd_all/actions/runs/5444296178).

See related upstream issue https://github.com/facebookresearch/detectron2/issues/5010.

Until upstream is fixed, `pip install -U "pillow<10.0.0"` helps.

**Comment by bertsky** [comment]
Strange that this did not hit us in the Docker build (also Py38).

Since it's unlikely this will get fixed in detectron2 any time soon (last release is from 2021), but we do not use this anywhere else in ocrd_all, would you recommend adding `pillow<10.0` here in requirements.txt?

**Comment by stweil** [comment]
Pillow 10.0.0 (which causes the breakage) was released on July 1, so it's not surprising that your or my previous builds passed fine. ~And yes, updating the requirements seems to be the only possible solution.~ Instead of updating the requirements (which would cause downgrades of `pillow` during the build process), it might be better to patch `detectron2` after it was installed.

**Comment by bertsky** [comment]
> was released on July 1, so it's not surprising that your or my previous builds passed fine.

It _is_ surprising – the latest Docker build is just [2h ago](https://github.com/OCR-D/ocrd_all/runs/14737204166).

> Instead of updating the requirements (which would cause downgrades of `pillow` during the build process), it might be better to patch `detectron2` after it was installed.

I would not know how to do this (properly). Using `make deps`, Detectron2 gets pulled from git and then compiled as a temporary wheel before getting installed into the current venv...

**Comment by bertsky** [comment]
I think I found a clean way.

Can you please try #28?

**Comment by stweil** [comment]
The pull requests #27 and #28 basically do the same thing to fix this issue. They only use slightly different ways to find the location of the installed detectron2 and to patch the code. It's your choice which one you prefer.

**Comment by rayryeng** [comment]
`detectron2` was recently updated (July 6, 2023) so that this issue is now fixed. You should be able to use Pillow==10.0.0 now.

https://github.com/facebookresearch/detectron2/commit/ff53992b1985b63bd3262b5a36167098e3dada02

**Comment by bertsky** [comment]
Thanks @rayryeng for letting me know!

Unfortunately, we still require released version [v0.6](https://github.com/facebookresearch/detectron2/releases/tag/v0.6) here, and there has been no release since then for over 2 years. I cannot see what ramifications the switch to master would have for (the performance of) all the models that we redistribute here...
