### ISSUE TITLE
Dockerimage (ghrc) and Dockerfile (locally) not working

### ISSUE THREAD

**Issue by joschrew** [bertsky/ocrd_detectron2#30]
The latest dockerimage (ghcr.io/bertsky/ocrd_detectron2) is not working for me, it does not contain ocrd-detectron2-segment executable. When trying to create the image myself with `make docker` the executable is there, but running `ocrd-detectron2-segment --help` I get the following ([known](https://github.com/facebookresearch/detectron2/pull/5011)) error:
 `AttributeError: module 'PIL.Image' has no attribute 'LINEAR'`.
I tried to limit pillow to 9.5.0 with requirements.txt, but pillow 10.something is installed anyway.

**Comment by bertsky** [comment]
The problem was twofold: core itself needed an update for Pillow 10 (done as of v2.69), but here a change was needed as well. Everything should be fixed in the current version.
